default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: case_v360_development

test:
  <<: *default
  database: case_v360_test

production:
  <<: *default
  database: case_v360_production

cable:
  <<: *default
  database: case_v360_cable

queue:
  <<: *default
  database: case_v360_queue

cache:
  <<: *default
  database: case_v360_cache